#include <iostream>
#include <string>

#include <faiss/IndexFlat.h>
#include <faiss/IndexIVFFlat.h>
#include <faiss/impl/FaissAssert.h>
#include <faiss/index_io.h>
#include <faiss/invlists/InvertedListsIOHook.h>
#include <faiss/utils/random.h>

#include "faiss_s3.h"
#include "lib.rs.h" // generated by cxxbridge

void create_example_ivf_index(rust::Str index_file_name) {
  std::cout << "Creating example IVF index in " << index_file_name << std::endl;
  const size_t VEC_DIM = 128;       // Vector dimension
  const size_t N_CLUSTERS = 100;    // Number of IVF clusters
  const size_t N_VECTORS = 100'000; // Number of vectors to index

  // Create index, default invert list implementation is memory
  faiss::IndexFlatL2 quantizer(VEC_DIM);
  faiss::IndexIVFFlat index(&quantizer, VEC_DIM, N_CLUSTERS);
  index.verbose = true;

  // Generate random vectors
  std::vector<float> xb(VEC_DIM * N_VECTORS);
  faiss::float_rand(xb.data(), VEC_DIM * N_VECTORS, 12345);

  index.train(N_VECTORS, xb.data());
  index.add(N_VECTORS, xb.data());

  // NOTE: rust::Str.data() does not have null terminator
  // https://cxx.rs/binding/str.html
  faiss::write_index(&index, std::string(index_file_name).c_str());
}