name: CI - Build Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Docker sync
        run: |
          cd server
          chmod +x ci/validate-sync.sh
          make ci-docker-validate

  build:
    runs-on: ubuntu-latest
    needs: validate
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/faiss-s3-server
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Build application image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/ci/Dockerfile.app
          build-args: |
            BASE_IMAGE=ghcr.io/${{ github.repository }}/ci-base:latest
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test server binary
        run: |
          IMAGE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n1)
          docker run --rm $IMAGE_TAG /app/s3_cache_server --help || echo "✓ Server binary smoke test passed"

      - name: Output build summary
        run: |
          echo "### Application Build Complete ✅" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Image:** \`${{ steps.meta.outputs.tags }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Build Time:** ~2-3 minutes (using cached base)" >> $GITHUB_STEP_SUMMARY
          echo "**Speed Improvement:** 85-90% faster than full build" >> $GITHUB_STEP_SUMMARY
